spring.application.name=server
spring.datasource.url=jdbc:mysql://localhost:3306/TU_BASE_DE_DATOS
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_CONTRASEÑA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=EsUnaContrasenyaPerDefecteMentresDesenvolupo!!Cambila!!MillorEncaraFesUnaVariableDeEntorn

# Configuracio d'usuaris per defecte
app.default.admin.password=admin1234
# Si esta en true, generara 'test1' i 'test2' (usuaris simples) al arrancar l'aplicacio.
app.seed.testdata=true
app.seed.testdata.password=test1234